version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_PROXY_HOST=http://localhost:8080

  nifi-registry:
    image: apache/nifi-registry:latest
    ports:
      - "18080:18080"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  minio_data: